repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-ast
    -   id: fix-encoding-pragma
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: [--config=pyproject.toml]
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
    -   id: pycln
        args: [--config=pyproject.toml]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--settings-path=pyproject.toml]
-   repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.19
    hooks:
    - id: tflint
      args:
        - "--module"
        - "--deep"
        - "--config=.tflint.hcl"
    - id: terraform-validate
    - id: terraform-fmt