site_name: AINewsTracker

theme:
  name: material
  palette:
    primary: green
    accent: purple
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - mkdocstrings
  - search
  - build_plantuml:
      render: 'server'
      server: 'http://www.plantuml.com/plantuml'
      output_format: 'svg'
      diagram_root: 'docs/diagrams'
      output_folder: 'out'
      input_folder: 'src'
      theme_enabled: true


nav:
  - Home: index.md
  - About: about.md
  - Getting Started: getting-started.md
  - Explanation: explanation.md
  - Examples: example.md
  - API Reference: api.md
  - Diagram: diagrams.md
  - Reference: refences.md
  - Contacts: contact.md
  - Tutorials: tutorials.md
