global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape metrics from the web application (FastAPI)
  # Adjust the target according to the actual setup of your FastAPI application
  - job_name: 'web'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['web:8000']

  # Scrape metrics from MongoDB
  # Note that MongoDB needs to have an exporter for Prometheus to be able to scrape metrics
  # Adjust the target according to the actual setup of your MongoDB exporter
  - job_name: 'mongodb'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['mongo:27017']

  # Scrape metrics from Redis
  # Note that Redis needs to have an exporter for Prometheus to be able to scrape metrics
  # Adjust the target according to the actual setup of your Redis exporter
  - job_name: 'redis'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['redis:6379']
